"""Loop a 4-pose dance: crouch → extend-up-left → crouch → extend-up-right → repeat.

Pose names are looked up in poses.json. Record them first with record_poses.py.

Edit the constants below, then run:
  python dance.py
"""

import json
import os
import time

from pylx16a.lx16a import LX16A, ServoTimeoutError

from util import advance_keyframe_sequence


# ─────────────────────────────────────────────
#  TUNING CONSTANTS
# ─────────────────────────────────────────────

POSE_CROUCH = "crouch"
POSE_EXTEND_LEFT = "extend_up_left"
# extend_up_right is auto-generated by mirroring extend_up_left across the body.

# Duration (ms) for each transition.
CROUCH_TO_EXTEND_MS = 500
EXTEND_TO_CROUCH_MS = 500

# 0 = loop forever; N > 0 = N full cycles then stop.
CYCLES = 0

# ─────────────────────────────────────────────


POSES_FILE = "poses.json"
TIME_STEP = 0.02

SERVO_IDS = {
    "left_rear": 5,
    "left_front": 4,
    "left_hip": 6,
    "right_rear": 2,
    "right_front": 3,
    "right_hip": 1,
}

# Mirror axes for each joint pair — derived from SERVO_CONFIG limits in main.py.
# right_angle = 2 * axis - left_angle (and vice versa).
MIRROR_AXES = {
    "front": 146.4,
    "rear": 151.32,
    "hip": 141.06,
}


def mirror_pose(pose):
    """Flip a full-body pose across the sagittal plane: left↔right swap + angle mirror."""
    out = {}
    for name, angle in pose.items():
        side, part = name.split("_", 1)
        other = "right" if side == "left" else "left"
        out[f"{other}_{part}"] = round(2 * MIRROR_AXES[part] - angle, 2)
    return out


def main():
    if not os.path.exists(POSES_FILE):
        raise SystemExit(f"{POSES_FILE} not found")
    with open(POSES_FILE) as f:
        poses = json.load(f)

    required = [POSE_CROUCH, POSE_EXTEND_LEFT]
    missing = [n for n in required if n not in poses]
    if missing:
        raise SystemExit(f"missing poses in {POSES_FILE}: {missing}")

    extend_right = mirror_pose(poses[POSE_EXTEND_LEFT])

    keyframes = [
        {
            "servo_angles": poses[POSE_EXTEND_LEFT],
            "max_duration": CROUCH_TO_EXTEND_MS,
            "ease": "smooth",
        },
        {
            "servo_angles": poses[POSE_CROUCH],
            "max_duration": EXTEND_TO_CROUCH_MS,
            "ease": "smooth",
        },
        {
            "servo_angles": extend_right,
            "max_duration": CROUCH_TO_EXTEND_MS,
            "ease": "smooth",
        },
        {
            "servo_angles": poses[POSE_CROUCH],
            "max_duration": EXTEND_TO_CROUCH_MS,
            "ease": "smooth",
        },
    ]
    cycle_s = sum(kf["max_duration"] for kf in keyframes) / 1000

    LX16A.initialize("/dev/ttyUSB0")
    try:
        servo_objs = {name: LX16A(sid) for name, sid in SERVO_IDS.items()}
    except ServoTimeoutError as e:
        raise SystemExit(f"Servo {e.id_} not responding.")

    servo_map = {
        name: {"id": SERVO_IDS[name], "servo": s} for name, s in servo_objs.items()
    }

    initial_pose = {name: servo_objs[name].get_physical_angle() for name in SERVO_IDS}

    print(
        f"dance cycle: {cycle_s:.2f}s  "
        f"({'looping' if CYCLES == 0 else f'{CYCLES} cycles'})"
    )
    print("Ctrl-C to stop")

    t = 0.0
    step = 0
    total_s = CYCLES * cycle_s if CYCLES > 0 else float("inf")
    try:
        for servo in servo_objs.values():
            servo.enable_torque()
        while t < total_s:
            _, step = advance_keyframe_sequence(
                servo_map,
                keyframes,
                step,
                t,
                time_step=TIME_STEP,
                speed_factor=1,
                prior_pose=initial_pose,
            )
            t += TIME_STEP
            time.sleep(TIME_STEP)
    except KeyboardInterrupt:
        print("\nstopped")
    finally:
        for servo in servo_objs.values():
            servo.disable_torque()


if __name__ == "__main__":
    main()
